import jstz from 'jstz'

const curTimezone = jstz.determine().name()
const timezoneArr = [
  'America/New_York',
  'America/Los_Angeles',
  'America/Chicago',
  'America/Phoenix',
  'America/Toronto',
  'America/Vancouver',
  'America/Argentina/Buenos_Aires',
  'America/El_Salvador',
  'America/Sao_Paulo',
  'America/Bogota',
  'America/Caracas',
  'Europe/Moscow',
  'Europe/Athens',
  'Europe/Belgrade',
  'Europe/Berlin',
  'Europe/London',
  'Europe/Luxembourg',
  'Europe/Madrid',
  'Europe/Paris',
  'Europe/Rome',
  'Europe/Warsaw',
  'Europe/Istanbul',
  'Europe/Zurich',
  'Australia/Sydney',
  'Australia/Brisbane',
  'Australia/Adelaide',
  'Australia/ACT',
  'Asia/Almaty',
  'Asia/Ashkhabad',
  'Asia/Tokyo',
  'Asia/Taipei',
  'Asia/Singapore',
  'Asia/Shanghai',
  'Asia/Seoul',
  'Asia/Tehran',
  'Asia/Dubai',
  'Asia/Kolkata',
  'Asia/Hong_Kong',
  'Asia/Bangkok',
  'Asia/Chongqing',
  'Asia/Jerusalem',
  'Asia/Kuwait',
  'Asia/Muscat',
  'Asia/Qatar',
  'Asia/Riyadh',
  'Pacific/Auckland',
  'Pacific/Chatham',
  'Pacific/Fakaofo',
  'Pacific/Honolulu',
  'America/Mexico_City',
  'Africa/Cairo',
  'Africa/Johannesburg',
  'Asia/Kathmandu',
  'US/Mountain',
]
let timezone = curTimezone
if (timezoneArr.indexOf(curTimezone) === -1) {
  timezone = 'Asia/Shanghai'
}

export default timezone
